// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConfigHandle : RemoteTableHandle<EventContext, Config>
        {
            protected override string RemoteTableName => "config";

            public sealed class VersionUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Config row) => row.Version;

                public VersionUniqueIndex(ConfigHandle table) : base(table) { }
            }

            public readonly VersionUniqueIndex Version;

            internal ConfigHandle(DbConnection conn) : base(conn)
            {
                Version = new(this);
            }
        }

        public readonly ConfigHandle Config;
    }
}
