// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class InventoryHandle : RemoteTableHandle<EventContext, InventoryComponent>
        {
            protected override string RemoteTableName => "inventory";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(InventoryComponent row) => row.EntityId;

                public EntityIdUniqueIndex(InventoryHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal InventoryHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(InventoryComponent row) => row.EntityId;
        }

        public readonly InventoryHandle Inventory;
    }
}
