// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHandle : RemoteTableHandle<EventContext, PlayerComponent>
        {
            protected override string RemoteTableName => "player";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerComponent row) => row.EntityId;

                public EntityIdUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class OwnerIdUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(PlayerComponent row) => row.OwnerId;

                public OwnerIdUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly OwnerIdUniqueIndex OwnerId;

            public sealed class UsernameUniqueIndex : UniqueIndexBase<string>
            {
                protected override string GetKey(PlayerComponent row) => row.Username;

                public UsernameUniqueIndex(PlayerHandle table) : base(table) { }
            }

            public readonly UsernameUniqueIndex Username;

            internal PlayerHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                OwnerId = new(this);
                Username = new(this);
            }

            protected override object GetPrimaryKey(PlayerComponent row) => row.EntityId;
        }

        public readonly PlayerHandle Player;
    }
}
