// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TradeHandle : RemoteTableHandle<EventContext, TradeSessionComponent>
        {
            protected override string RemoteTableName => "trade";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TradeSessionComponent row) => row.EntityId;

                public EntityIdUniqueIndex(TradeHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal TradeHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(TradeSessionComponent row) => row.EntityId;
        }

        public readonly TradeHandle Trade;
    }
}
