// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TransformHandle : RemoteTableHandle<EventContext, TransformComponent>
        {
            protected override string RemoteTableName => "transform";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TransformComponent row) => row.EntityId;

                public EntityIdUniqueIndex(TransformHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal TransformHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(TransformComponent row) => row.EntityId;
        }

        public readonly TransformHandle Transform;
    }
}
