// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AnimationComponent
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "moving")]
        public bool Moving;
        [DataMember(Name = "action_target_entity_id")]
        public ulong ActionTargetEntityId;

        public AnimationComponent(
            ulong EntityId,
            bool Moving,
            ulong ActionTargetEntityId
        )
        {
            this.EntityId = EntityId;
            this.Moving = Moving;
            this.ActionTargetEntityId = ActionTargetEntityId;
        }

        public AnimationComponent()
        {
        }
    }
}
