// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ChunkData
    {
        [DataMember(Name = "chunk_id")]
        public ulong ChunkId;
        [DataMember(Name = "data")]
        public System.Collections.Generic.List<byte> Data;
        [DataMember(Name = "grass")]
        public System.Collections.Generic.List<Grass> Grass;
        [DataMember(Name = "trees")]
        public System.Collections.Generic.List<Tree> Trees;
        [DataMember(Name = "deposits")]
        public System.Collections.Generic.List<Deposit> Deposits;

        public ChunkData(
            ulong ChunkId,
            System.Collections.Generic.List<byte> Data,
            System.Collections.Generic.List<Grass> Grass,
            System.Collections.Generic.List<Tree> Trees,
            System.Collections.Generic.List<Deposit> Deposits
        )
        {
            this.ChunkId = ChunkId;
            this.Data = Data;
            this.Grass = Grass;
            this.Trees = Trees;
            this.Deposits = Deposits;
        }

        public ChunkData()
        {
            this.Data = new();
            this.Grass = new();
            this.Trees = new();
            this.Deposits = new();
        }
    }
}
