// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerComponent
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "owner_id")]
        public SpacetimeDB.Identity OwnerId;
        [DataMember(Name = "username")]
        public string Username;
        [DataMember(Name = "creation_time")]
        public ulong CreationTime;

        public PlayerComponent(
            ulong EntityId,
            SpacetimeDB.Identity OwnerId,
            string Username,
            ulong CreationTime
        )
        {
            this.EntityId = EntityId;
            this.OwnerId = OwnerId;
            this.Username = Username;
            this.CreationTime = CreationTime;
        }

        public PlayerComponent()
        {
            this.Username = "";
        }
    }
}
