// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerChatMessage
    {
        [DataMember(Name = "player_id")]
        public ulong PlayerId;
        [DataMember(Name = "msg_time")]
        public ulong MsgTime;
        [DataMember(Name = "message")]
        public string Message;

        public PlayerChatMessage(
            ulong PlayerId,
            ulong MsgTime,
            string Message
        )
        {
            this.PlayerId = PlayerId;
            this.MsgTime = MsgTime;
            this.Message = Message;
        }

        public PlayerChatMessage()
        {
            this.Message = "";
        }
    }
}
