// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ServerGlobals
    {
        [DataMember(Name = "version")]
        public uint Version;
        [DataMember(Name = "entity_id_counter")]
        public ulong EntityIdCounter;

        public ServerGlobals(
            uint Version,
            ulong EntityIdCounter
        )
        {
            this.Version = Version;
            this.EntityIdCounter = EntityIdCounter;
        }

        public ServerGlobals()
        {
        }
    }
}
