// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class StdbQuaternion
    {
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "z")]
        public float Z;
        [DataMember(Name = "w")]
        public float W;

        public StdbQuaternion(
            float Y,
            float X,
            float Z,
            float W
        )
        {
            this.Y = Y;
            this.X = X;
            this.Z = Z;
            this.W = W;
        }

        public StdbQuaternion()
        {
        }
    }
}
