// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CheckChunksForAllPlayersHandler(ReducerEventContext ctx, CheckChunkForAllPlayersTimer timer);
        public event CheckChunksForAllPlayersHandler? OnCheckChunksForAllPlayers;

        public void CheckChunksForAllPlayers(CheckChunkForAllPlayersTimer timer)
        {
            conn.InternalCallReducer(new Reducer.CheckChunksForAllPlayers(timer), this.SetCallReducerFlags.CheckChunksForAllPlayersFlags);
        }

        public bool InvokeCheckChunksForAllPlayers(ReducerEventContext ctx, Reducer.CheckChunksForAllPlayers args)
        {
            if (OnCheckChunksForAllPlayers == null) return false;
            OnCheckChunksForAllPlayers(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CheckChunksForAllPlayers : Reducer, IReducerArgs
        {
            [DataMember(Name = "_timer")]
            public CheckChunkForAllPlayersTimer Timer;

            public CheckChunksForAllPlayers(CheckChunkForAllPlayersTimer Timer)
            {
                this.Timer = Timer;
            }

            public CheckChunksForAllPlayers()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "check_chunks_for_all_players";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CheckChunksForAllPlayersFlags;
        public void CheckChunksForAllPlayers(CallReducerFlags flags) => CheckChunksForAllPlayersFlags = flags;
    }
}
