// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CreateNewPlayerHandler(ReducerEventContext ctx, StdbVector3 startPos, StdbQuaternion startRot, string username);
        public event CreateNewPlayerHandler? OnCreateNewPlayer;

        public void CreateNewPlayer(StdbVector3 startPos, StdbQuaternion startRot, string username)
        {
            conn.InternalCallReducer(new Reducer.CreateNewPlayer(startPos, startRot, username), this.SetCallReducerFlags.CreateNewPlayerFlags);
        }

        public bool InvokeCreateNewPlayer(ReducerEventContext ctx, Reducer.CreateNewPlayer args)
        {
            if (OnCreateNewPlayer == null) return false;
            OnCreateNewPlayer(
                ctx,
                args.StartPos,
                args.StartRot,
                args.Username
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CreateNewPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "start_pos")]
            public StdbVector3 StartPos;
            [DataMember(Name = "start_rot")]
            public StdbQuaternion StartRot;
            [DataMember(Name = "username")]
            public string Username;

            public CreateNewPlayer(
                StdbVector3 StartPos,
                StdbQuaternion StartRot,
                string Username
            )
            {
                this.StartPos = StartPos;
                this.StartRot = StartRot;
                this.Username = Username;
            }

            public CreateNewPlayer()
            {
                this.StartPos = new();
                this.StartRot = new();
                this.Username = "";
            }

            string IReducerArgs.ReducerName => "create_new_player";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CreateNewPlayerFlags;
        public void CreateNewPlayer(CallReducerFlags flags) => CreateNewPlayerFlags = flags;
    }
}
