// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ExtractHandler(ReducerEventContext ctx, ulong entityId, ulong resourceEntityId);
        public event ExtractHandler? OnExtract;

        public void Extract(ulong entityId, ulong resourceEntityId)
        {
            conn.InternalCallReducer(new Reducer.Extract(entityId, resourceEntityId), this.SetCallReducerFlags.ExtractFlags);
        }

        public bool InvokeExtract(ReducerEventContext ctx, Reducer.Extract args)
        {
            if (OnExtract == null) return false;
            OnExtract(
                ctx,
                args.EntityId,
                args.ResourceEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Extract : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;
            [DataMember(Name = "resource_entity_id")]
            public ulong ResourceEntityId;

            public Extract(
                ulong EntityId,
                ulong ResourceEntityId
            )
            {
                this.EntityId = EntityId;
                this.ResourceEntityId = ResourceEntityId;
            }

            public Extract()
            {
            }

            string IReducerArgs.ReducerName => "extract";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ExtractFlags;
        public void Extract(CallReducerFlags flags) => ExtractFlags = flags;
    }
}
