// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveNpcHandler(ReducerEventContext ctx, ulong timestamp, ulong entityId, StdbVector3 pos, StdbQuaternion rot, ulong duration);
        public event MoveNpcHandler? OnMoveNpc;

        public void MoveNpc(ulong timestamp, ulong entityId, StdbVector3 pos, StdbQuaternion rot, ulong duration)
        {
            conn.InternalCallReducer(new Reducer.MoveNpc(timestamp, entityId, pos, rot, duration), this.SetCallReducerFlags.MoveNpcFlags);
        }

        public bool InvokeMoveNpc(ReducerEventContext ctx, Reducer.MoveNpc args)
        {
            if (OnMoveNpc == null) return false;
            OnMoveNpc(
                ctx,
                args.Timestamp,
                args.EntityId,
                args.Pos,
                args.Rot,
                args.Duration
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveNpc : Reducer, IReducerArgs
        {
            [DataMember(Name = "timestamp")]
            public ulong Timestamp;
            [DataMember(Name = "entity_id")]
            public ulong EntityId;
            [DataMember(Name = "pos")]
            public StdbVector3 Pos;
            [DataMember(Name = "rot")]
            public StdbQuaternion Rot;
            [DataMember(Name = "duration")]
            public ulong Duration;

            public MoveNpc(
                ulong Timestamp,
                ulong EntityId,
                StdbVector3 Pos,
                StdbQuaternion Rot,
                ulong Duration
            )
            {
                this.Timestamp = Timestamp;
                this.EntityId = EntityId;
                this.Pos = Pos;
                this.Rot = Rot;
                this.Duration = Duration;
            }

            public MoveNpc()
            {
                this.Pos = new();
                this.Rot = new();
            }

            string IReducerArgs.ReducerName => "move_npc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MoveNpcFlags;
        public void MoveNpc(CallReducerFlags flags) => MoveNpcFlags = flags;
    }
}
