// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateAnimationHandler(ReducerEventContext ctx, ulong entityId, bool moving, ulong actionTargetEntityId);
        public event UpdateAnimationHandler? OnUpdateAnimation;

        public void UpdateAnimation(ulong entityId, bool moving, ulong actionTargetEntityId)
        {
            conn.InternalCallReducer(new Reducer.UpdateAnimation(entityId, moving, actionTargetEntityId), this.SetCallReducerFlags.UpdateAnimationFlags);
        }

        public bool InvokeUpdateAnimation(ReducerEventContext ctx, Reducer.UpdateAnimation args)
        {
            if (OnUpdateAnimation == null) return false;
            OnUpdateAnimation(
                ctx,
                args.EntityId,
                args.Moving,
                args.ActionTargetEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateAnimation : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;
            [DataMember(Name = "moving")]
            public bool Moving;
            [DataMember(Name = "action_target_entity_id")]
            public ulong ActionTargetEntityId;

            public UpdateAnimation(
                ulong EntityId,
                bool Moving,
                ulong ActionTargetEntityId
            )
            {
                this.EntityId = EntityId;
                this.Moving = Moving;
                this.ActionTargetEntityId = ActionTargetEntityId;
            }

            public UpdateAnimation()
            {
            }

            string IReducerArgs.ReducerName => "update_animation";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateAnimationFlags;
        public void UpdateAnimation(CallReducerFlags flags) => UpdateAnimationFlags = flags;
    }
}
