// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ActiveTradeHandle : RemoteTableHandle<EventContext, ActiveTradeComponent>
        {
            protected override string RemoteTableName => "active_trade";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ActiveTradeComponent row) => row.EntityId;

                public EntityIdUniqueIndex(ActiveTradeHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal ActiveTradeHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(ActiveTradeComponent row) => row.EntityId;
        }

        public readonly ActiveTradeHandle ActiveTrade;
    }
}
