// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CheckChunksForAllPlayersTimerHandle : RemoteTableHandle<EventContext, CheckChunkForAllPlayersTimer>
        {
            protected override string RemoteTableName => "check_chunks_for_all_players_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CheckChunkForAllPlayersTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(CheckChunksForAllPlayersTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal CheckChunksForAllPlayersTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(CheckChunkForAllPlayersTimer row) => row.ScheduledId;
        }

        public readonly CheckChunksForAllPlayersTimerHandle CheckChunksForAllPlayersTimer;
    }
}
