// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChunkHandle : RemoteTableHandle<EventContext, Chunk>
        {
            protected override string RemoteTableName => "chunk";

            public sealed class ChunkIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(Chunk row) => row.ChunkId;

                public ChunkIdUniqueIndex(ChunkHandle table) : base(table) { }
            }

            public readonly ChunkIdUniqueIndex ChunkId;

            internal ChunkHandle(DbConnection conn) : base(conn)
            {
                ChunkId = new(this);
            }
        }

        public readonly ChunkHandle Chunk;
    }
}
