// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChunkDataHandle : RemoteTableHandle<EventContext, ChunkData>
        {
            protected override string RemoteTableName => "chunk_data";

            public sealed class ChunkIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ChunkData row) => row.ChunkId;

                public ChunkIdUniqueIndex(ChunkDataHandle table) : base(table) { }
            }

            public readonly ChunkIdUniqueIndex ChunkId;

            internal ChunkDataHandle(DbConnection conn) : base(conn)
            {
                ChunkId = new(this);
            }

            protected override object GetPrimaryKey(ChunkData row) => row.ChunkId;
        }

        public readonly ChunkDataHandle ChunkData;
    }
}
