// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DespawnNpcsTimerHandle : RemoteTableHandle<EventContext, DespawnNpcsTimer>
        {
            protected override string RemoteTableName => "despawn_npcs_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DespawnNpcsTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(DespawnNpcsTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal DespawnNpcsTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(DespawnNpcsTimer row) => row.ScheduledId;
        }

        public readonly DespawnNpcsTimerHandle DespawnNpcsTimer;
    }
}
