// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcHandle : RemoteTableHandle<EventContext, NpcComponent>
        {
            protected override string RemoteTableName => "npc";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(NpcComponent row) => row.EntityId;

                public EntityIdUniqueIndex(NpcHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal NpcHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }
        }

        public readonly NpcHandle Npc;
    }
}
