// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerLoginHandle : RemoteTableHandle<EventContext, PlayerLoginComponent>
        {
            protected override string RemoteTableName => "player_login";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerLoginComponent row) => row.EntityId;

                public EntityIdUniqueIndex(PlayerLoginHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal PlayerLoginHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(PlayerLoginComponent row) => row.EntityId;
        }

        public readonly PlayerLoginHandle PlayerLogin;
    }
}
