// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ResourceHandle : RemoteTableHandle<EventContext, ResourceComponent>
        {
            protected override string RemoteTableName => "resource";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ResourceComponent row) => row.EntityId;

                public EntityIdUniqueIndex(ResourceHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal ResourceHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(ResourceComponent row) => row.EntityId;
        }

        public readonly ResourceHandle Resource;
    }
}
