// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ServerGlobalsHandle : RemoteTableHandle<EventContext, ServerGlobals>
        {
            protected override string RemoteTableName => "server_globals";

            public sealed class VersionUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(ServerGlobals row) => row.Version;

                public VersionUniqueIndex(ServerGlobalsHandle table) : base(table) { }
            }

            public readonly VersionUniqueIndex Version;

            internal ServerGlobalsHandle(DbConnection conn) : base(conn)
            {
                Version = new(this);
            }
        }

        public readonly ServerGlobalsHandle ServerGlobals;
    }
}
