// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SpawnNpcsTimerHandle : RemoteTableHandle<EventContext, SpawnNpcsTimer>
        {
            protected override string RemoteTableName => "spawn_npcs_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(SpawnNpcsTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(SpawnNpcsTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal SpawnNpcsTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(SpawnNpcsTimer row) => row.ScheduledId;
        }

        public readonly SpawnNpcsTimerHandle SpawnNpcsTimer;
    }
}
