// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddItemToInventoryHandler(ReducerEventContext ctx, ulong entityId, uint itemId, int pocketIdx, int itemCount);
        public event AddItemToInventoryHandler? OnAddItemToInventory;

        public void AddItemToInventory(ulong entityId, uint itemId, int pocketIdx, int itemCount)
        {
            conn.InternalCallReducer(new Reducer.AddItemToInventory(entityId, itemId, pocketIdx, itemCount), this.SetCallReducerFlags.AddItemToInventoryFlags);
        }

        public bool InvokeAddItemToInventory(ReducerEventContext ctx, Reducer.AddItemToInventory args)
        {
            if (OnAddItemToInventory == null) return false;
            OnAddItemToInventory(
                ctx,
                args.EntityId,
                args.ItemId,
                args.PocketIdx,
                args.ItemCount
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddItemToInventory : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;
            [DataMember(Name = "item_id")]
            public uint ItemId;
            [DataMember(Name = "pocket_idx")]
            public int PocketIdx;
            [DataMember(Name = "item_count")]
            public int ItemCount;

            public AddItemToInventory(
                ulong EntityId,
                uint ItemId,
                int PocketIdx,
                int ItemCount
            )
            {
                this.EntityId = EntityId;
                this.ItemId = ItemId;
                this.PocketIdx = PocketIdx;
                this.ItemCount = ItemCount;
            }

            public AddItemToInventory()
            {
            }

            string IReducerArgs.ReducerName => "add_item_to_inventory";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddItemToInventoryFlags;
        public void AddItemToInventory(CallReducerFlags flags) => AddItemToInventoryFlags = flags;
    }
}
