// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddToTradeHandler(ReducerEventContext ctx, ulong participantEntityId, uint sourcePocketId, uint destPocketId);
        public event AddToTradeHandler? OnAddToTrade;

        public void AddToTrade(ulong participantEntityId, uint sourcePocketId, uint destPocketId)
        {
            conn.InternalCallReducer(new Reducer.AddToTrade(participantEntityId, sourcePocketId, destPocketId), this.SetCallReducerFlags.AddToTradeFlags);
        }

        public bool InvokeAddToTrade(ReducerEventContext ctx, Reducer.AddToTrade args)
        {
            if (OnAddToTrade == null) return false;
            OnAddToTrade(
                ctx,
                args.ParticipantEntityId,
                args.SourcePocketId,
                args.DestPocketId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddToTrade : Reducer, IReducerArgs
        {
            [DataMember(Name = "participant_entity_id")]
            public ulong ParticipantEntityId;
            [DataMember(Name = "source_pocket_id")]
            public uint SourcePocketId;
            [DataMember(Name = "dest_pocket_id")]
            public uint DestPocketId;

            public AddToTrade(
                ulong ParticipantEntityId,
                uint SourcePocketId,
                uint DestPocketId
            )
            {
                this.ParticipantEntityId = ParticipantEntityId;
                this.SourcePocketId = SourcePocketId;
                this.DestPocketId = DestPocketId;
            }

            public AddToTrade()
            {
            }

            string IReducerArgs.ReducerName => "add_to_trade";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddToTradeFlags;
        public void AddToTrade(CallReducerFlags flags) => AddToTradeFlags = flags;
    }
}
