// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DespawnNpcsHandler(ReducerEventContext ctx, DespawnNpcsTimer timer);
        public event DespawnNpcsHandler? OnDespawnNpcs;

        public void DespawnNpcs(DespawnNpcsTimer timer)
        {
            conn.InternalCallReducer(new Reducer.DespawnNpcs(timer), this.SetCallReducerFlags.DespawnNpcsFlags);
        }

        public bool InvokeDespawnNpcs(ReducerEventContext ctx, Reducer.DespawnNpcs args)
        {
            if (OnDespawnNpcs == null) return false;
            OnDespawnNpcs(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DespawnNpcs : Reducer, IReducerArgs
        {
            [DataMember(Name = "_timer")]
            public DespawnNpcsTimer Timer;

            public DespawnNpcs(DespawnNpcsTimer Timer)
            {
                this.Timer = Timer;
            }

            public DespawnNpcs()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "despawn_npcs";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DespawnNpcsFlags;
        public void DespawnNpcs(CallReducerFlags flags) => DespawnNpcsFlags = flags;
    }
}
