// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DumpInventoryHandler(ReducerEventContext ctx, ulong entityId);
        public event DumpInventoryHandler? OnDumpInventory;

        public void DumpInventory(ulong entityId)
        {
            conn.InternalCallReducer(new Reducer.DumpInventory(entityId), this.SetCallReducerFlags.DumpInventoryFlags);
        }

        public bool InvokeDumpInventory(ReducerEventContext ctx, Reducer.DumpInventory args)
        {
            if (OnDumpInventory == null) return false;
            OnDumpInventory(
                ctx,
                args.EntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DumpInventory : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;

            public DumpInventory(ulong EntityId)
            {
                this.EntityId = EntityId;
            }

            public DumpInventory()
            {
            }

            string IReducerArgs.ReducerName => "dump_inventory";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DumpInventoryFlags;
        public void DumpInventory(CallReducerFlags flags) => DumpInventoryFlags = flags;
    }
}
