// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InitiateTradeSessionHandler(ReducerEventContext ctx, ulong initiatorEntityId, ulong acceptorEntityId);
        public event InitiateTradeSessionHandler? OnInitiateTradeSession;

        public void InitiateTradeSession(ulong initiatorEntityId, ulong acceptorEntityId)
        {
            conn.InternalCallReducer(new Reducer.InitiateTradeSession(initiatorEntityId, acceptorEntityId), this.SetCallReducerFlags.InitiateTradeSessionFlags);
        }

        public bool InvokeInitiateTradeSession(ReducerEventContext ctx, Reducer.InitiateTradeSession args)
        {
            if (OnInitiateTradeSession == null) return false;
            OnInitiateTradeSession(
                ctx,
                args.InitiatorEntityId,
                args.AcceptorEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InitiateTradeSession : Reducer, IReducerArgs
        {
            [DataMember(Name = "initiator_entity_id")]
            public ulong InitiatorEntityId;
            [DataMember(Name = "acceptor_entity_id")]
            public ulong AcceptorEntityId;

            public InitiateTradeSession(
                ulong InitiatorEntityId,
                ulong AcceptorEntityId
            )
            {
                this.InitiatorEntityId = InitiatorEntityId;
                this.AcceptorEntityId = AcceptorEntityId;
            }

            public InitiateTradeSession()
            {
            }

            string IReducerArgs.ReducerName => "initiate_trade_session";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags InitiateTradeSessionFlags;
        public void InitiateTradeSession(CallReducerFlags flags) => InitiateTradeSessionFlags = flags;
    }
}
