// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveNpcsHandler(ReducerEventContext ctx, MoveNpcsTimer timer);
        public event MoveNpcsHandler? OnMoveNpcs;

        public void MoveNpcs(MoveNpcsTimer timer)
        {
            conn.InternalCallReducer(new Reducer.MoveNpcs(timer), this.SetCallReducerFlags.MoveNpcsFlags);
        }

        public bool InvokeMoveNpcs(ReducerEventContext ctx, Reducer.MoveNpcs args)
        {
            if (OnMoveNpcs == null) return false;
            OnMoveNpcs(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveNpcs : Reducer, IReducerArgs
        {
            [DataMember(Name = "_timer")]
            public MoveNpcsTimer Timer;

            public MoveNpcs(MoveNpcsTimer Timer)
            {
                this.Timer = Timer;
            }

            public MoveNpcs()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "move_npcs";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MoveNpcsFlags;
        public void MoveNpcs(CallReducerFlags flags) => MoveNpcsFlags = flags;
    }
}
