// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MoveOrSwapInventorySlotHandler(ReducerEventContext ctx, ulong playerEntityId, ulong inventoryEntityId, uint sourcePocketIdx, uint destPocketIdx);
        public event MoveOrSwapInventorySlotHandler? OnMoveOrSwapInventorySlot;

        public void MoveOrSwapInventorySlot(ulong playerEntityId, ulong inventoryEntityId, uint sourcePocketIdx, uint destPocketIdx)
        {
            conn.InternalCallReducer(new Reducer.MoveOrSwapInventorySlot(playerEntityId, inventoryEntityId, sourcePocketIdx, destPocketIdx), this.SetCallReducerFlags.MoveOrSwapInventorySlotFlags);
        }

        public bool InvokeMoveOrSwapInventorySlot(ReducerEventContext ctx, Reducer.MoveOrSwapInventorySlot args)
        {
            if (OnMoveOrSwapInventorySlot == null) return false;
            OnMoveOrSwapInventorySlot(
                ctx,
                args.PlayerEntityId,
                args.InventoryEntityId,
                args.SourcePocketIdx,
                args.DestPocketIdx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MoveOrSwapInventorySlot : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_entity_id")]
            public ulong PlayerEntityId;
            [DataMember(Name = "inventory_entity_id")]
            public ulong InventoryEntityId;
            [DataMember(Name = "source_pocket_idx")]
            public uint SourcePocketIdx;
            [DataMember(Name = "dest_pocket_idx")]
            public uint DestPocketIdx;

            public MoveOrSwapInventorySlot(
                ulong PlayerEntityId,
                ulong InventoryEntityId,
                uint SourcePocketIdx,
                uint DestPocketIdx
            )
            {
                this.PlayerEntityId = PlayerEntityId;
                this.InventoryEntityId = InventoryEntityId;
                this.SourcePocketIdx = SourcePocketIdx;
                this.DestPocketIdx = DestPocketIdx;
            }

            public MoveOrSwapInventorySlot()
            {
            }

            string IReducerArgs.ReducerName => "move_or_swap_inventory_slot";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MoveOrSwapInventorySlotFlags;
        public void MoveOrSwapInventorySlot(CallReducerFlags flags) => MoveOrSwapInventorySlotFlags = flags;
    }
}
