// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MovePlayerHandler(ReducerEventContext ctx, ulong entityId, StdbVector3 pos, StdbQuaternion rot);
        public event MovePlayerHandler? OnMovePlayer;

        public void MovePlayer(ulong entityId, StdbVector3 pos, StdbQuaternion rot)
        {
            conn.InternalCallReducer(new Reducer.MovePlayer(entityId, pos, rot), this.SetCallReducerFlags.MovePlayerFlags);
        }

        public bool InvokeMovePlayer(ReducerEventContext ctx, Reducer.MovePlayer args)
        {
            if (OnMovePlayer == null) return false;
            OnMovePlayer(
                ctx,
                args.EntityId,
                args.Pos,
                args.Rot
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MovePlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;
            [DataMember(Name = "pos")]
            public StdbVector3 Pos;
            [DataMember(Name = "rot")]
            public StdbQuaternion Rot;

            public MovePlayer(
                ulong EntityId,
                StdbVector3 Pos,
                StdbQuaternion Rot
            )
            {
                this.EntityId = EntityId;
                this.Pos = Pos;
                this.Rot = Rot;
            }

            public MovePlayer()
            {
                this.Pos = new();
                this.Rot = new();
            }

            string IReducerArgs.ReducerName => "move_player";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MovePlayerFlags;
        public void MovePlayer(CallReducerFlags flags) => MovePlayerFlags = flags;
    }
}
