// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerChatHandler(ReducerEventContext ctx, ulong playerId, string message);
        public event PlayerChatHandler? OnPlayerChat;

        public void PlayerChat(ulong playerId, string message)
        {
            conn.InternalCallReducer(new Reducer.PlayerChat(playerId, message), this.SetCallReducerFlags.PlayerChatFlags);
        }

        public bool InvokePlayerChat(ReducerEventContext ctx, Reducer.PlayerChat args)
        {
            if (OnPlayerChat == null) return false;
            OnPlayerChat(
                ctx,
                args.PlayerId,
                args.Message
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerChat : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_id")]
            public ulong PlayerId;
            [DataMember(Name = "message")]
            public string Message;

            public PlayerChat(
                ulong PlayerId,
                string Message
            )
            {
                this.PlayerId = PlayerId;
                this.Message = Message;
            }

            public PlayerChat()
            {
                this.Message = "";
            }

            string IReducerArgs.ReducerName => "player_chat";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerChatFlags;
        public void PlayerChat(CallReducerFlags flags) => PlayerChatFlags = flags;
    }
}
