// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerUpdateLoginStateHandler(ReducerEventContext ctx, bool loggedIn);
        public event PlayerUpdateLoginStateHandler? OnPlayerUpdateLoginState;

        public void PlayerUpdateLoginState(bool loggedIn)
        {
            conn.InternalCallReducer(new Reducer.PlayerUpdateLoginState(loggedIn), this.SetCallReducerFlags.PlayerUpdateLoginStateFlags);
        }

        public bool InvokePlayerUpdateLoginState(ReducerEventContext ctx, Reducer.PlayerUpdateLoginState args)
        {
            if (OnPlayerUpdateLoginState == null) return false;
            OnPlayerUpdateLoginState(
                ctx,
                args.LoggedIn
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerUpdateLoginState : Reducer, IReducerArgs
        {
            [DataMember(Name = "logged_in")]
            public bool LoggedIn;

            public PlayerUpdateLoginState(bool LoggedIn)
            {
                this.LoggedIn = LoggedIn;
            }

            public PlayerUpdateLoginState()
            {
            }

            string IReducerArgs.ReducerName => "player_update_login_state";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerUpdateLoginStateFlags;
        public void PlayerUpdateLoginState(CallReducerFlags flags) => PlayerUpdateLoginStateFlags = flags;
    }
}
