// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RefuseTradeHandler(ReducerEventContext ctx, ulong participantEntityId);
        public event RefuseTradeHandler? OnRefuseTrade;

        public void RefuseTrade(ulong participantEntityId)
        {
            conn.InternalCallReducer(new Reducer.RefuseTrade(participantEntityId), this.SetCallReducerFlags.RefuseTradeFlags);
        }

        public bool InvokeRefuseTrade(ReducerEventContext ctx, Reducer.RefuseTrade args)
        {
            if (OnRefuseTrade == null) return false;
            OnRefuseTrade(
                ctx,
                args.ParticipantEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RefuseTrade : Reducer, IReducerArgs
        {
            [DataMember(Name = "participant_entity_id")]
            public ulong ParticipantEntityId;

            public RefuseTrade(ulong ParticipantEntityId)
            {
                this.ParticipantEntityId = ParticipantEntityId;
            }

            public RefuseTrade()
            {
            }

            string IReducerArgs.ReducerName => "refuse_trade";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RefuseTradeFlags;
        public void RefuseTrade(CallReducerFlags flags) => RefuseTradeFlags = flags;
    }
}
