// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RemoveFromTradeHandler(ReducerEventContext ctx, ulong participantEntityId, uint sourcePocketId, uint destPocketId);
        public event RemoveFromTradeHandler? OnRemoveFromTrade;

        public void RemoveFromTrade(ulong participantEntityId, uint sourcePocketId, uint destPocketId)
        {
            conn.InternalCallReducer(new Reducer.RemoveFromTrade(participantEntityId, sourcePocketId, destPocketId), this.SetCallReducerFlags.RemoveFromTradeFlags);
        }

        public bool InvokeRemoveFromTrade(ReducerEventContext ctx, Reducer.RemoveFromTrade args)
        {
            if (OnRemoveFromTrade == null) return false;
            OnRemoveFromTrade(
                ctx,
                args.ParticipantEntityId,
                args.SourcePocketId,
                args.DestPocketId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RemoveFromTrade : Reducer, IReducerArgs
        {
            [DataMember(Name = "participant_entity_id")]
            public ulong ParticipantEntityId;
            [DataMember(Name = "source_pocket_id")]
            public uint SourcePocketId;
            [DataMember(Name = "dest_pocket_id")]
            public uint DestPocketId;

            public RemoveFromTrade(
                ulong ParticipantEntityId,
                uint SourcePocketId,
                uint DestPocketId
            )
            {
                this.ParticipantEntityId = ParticipantEntityId;
                this.SourcePocketId = SourcePocketId;
                this.DestPocketId = DestPocketId;
            }

            public RemoveFromTrade()
            {
            }

            string IReducerArgs.ReducerName => "remove_from_trade";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RemoveFromTradeFlags;
        public void RemoveFromTrade(CallReducerFlags flags) => RemoveFromTradeFlags = flags;
    }
}
