// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SpawnNpcsHandler(ReducerEventContext ctx, SpawnNpcsTimer timer);
        public event SpawnNpcsHandler? OnSpawnNpcs;

        public void SpawnNpcs(SpawnNpcsTimer timer)
        {
            conn.InternalCallReducer(new Reducer.SpawnNpcs(timer), this.SetCallReducerFlags.SpawnNpcsFlags);
        }

        public bool InvokeSpawnNpcs(ReducerEventContext ctx, Reducer.SpawnNpcs args)
        {
            if (OnSpawnNpcs == null) return false;
            OnSpawnNpcs(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SpawnNpcs : Reducer, IReducerArgs
        {
            [DataMember(Name = "_timer")]
            public SpawnNpcsTimer Timer;

            public SpawnNpcs(SpawnNpcsTimer Timer)
            {
                this.Timer = Timer;
            }

            public SpawnNpcs()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "spawn_npcs";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SpawnNpcsFlags;
        public void SpawnNpcs(CallReducerFlags flags) => SpawnNpcsFlags = flags;
    }
}
