// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ToggleAcceptTradeHandler(ReducerEventContext ctx, ulong participantEntityId);
        public event ToggleAcceptTradeHandler? OnToggleAcceptTrade;

        public void ToggleAcceptTrade(ulong participantEntityId)
        {
            conn.InternalCallReducer(new Reducer.ToggleAcceptTrade(participantEntityId), this.SetCallReducerFlags.ToggleAcceptTradeFlags);
        }

        public bool InvokeToggleAcceptTrade(ReducerEventContext ctx, Reducer.ToggleAcceptTrade args)
        {
            if (OnToggleAcceptTrade == null) return false;
            OnToggleAcceptTrade(
                ctx,
                args.ParticipantEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ToggleAcceptTrade : Reducer, IReducerArgs
        {
            [DataMember(Name = "participant_entity_id")]
            public ulong ParticipantEntityId;

            public ToggleAcceptTrade(ulong ParticipantEntityId)
            {
                this.ParticipantEntityId = ParticipantEntityId;
            }

            public ToggleAcceptTrade()
            {
            }

            string IReducerArgs.ReducerName => "toggle_accept_trade";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ToggleAcceptTradeFlags;
        public void ToggleAcceptTrade(CallReducerFlags flags) => ToggleAcceptTradeFlags = flags;
    }
}
