// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateNpcAnimationHandler(ReducerEventContext ctx, ulong timestamp, ulong entityId, bool moving, ulong actionTargetEntityId);
        public event UpdateNpcAnimationHandler? OnUpdateNpcAnimation;

        public void UpdateNpcAnimation(ulong timestamp, ulong entityId, bool moving, ulong actionTargetEntityId)
        {
            conn.InternalCallReducer(new Reducer.UpdateNpcAnimation(timestamp, entityId, moving, actionTargetEntityId), this.SetCallReducerFlags.UpdateNpcAnimationFlags);
        }

        public bool InvokeUpdateNpcAnimation(ReducerEventContext ctx, Reducer.UpdateNpcAnimation args)
        {
            if (OnUpdateNpcAnimation == null) return false;
            OnUpdateNpcAnimation(
                ctx,
                args.Timestamp,
                args.EntityId,
                args.Moving,
                args.ActionTargetEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateNpcAnimation : Reducer, IReducerArgs
        {
            [DataMember(Name = "timestamp")]
            public ulong Timestamp;
            [DataMember(Name = "entity_id")]
            public ulong EntityId;
            [DataMember(Name = "moving")]
            public bool Moving;
            [DataMember(Name = "action_target_entity_id")]
            public ulong ActionTargetEntityId;

            public UpdateNpcAnimation(
                ulong Timestamp,
                ulong EntityId,
                bool Moving,
                ulong ActionTargetEntityId
            )
            {
                this.Timestamp = Timestamp;
                this.EntityId = EntityId;
                this.Moving = Moving;
                this.ActionTargetEntityId = ActionTargetEntityId;
            }

            public UpdateNpcAnimation()
            {
            }

            string IReducerArgs.ReducerName => "update_npc_animation";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateNpcAnimationFlags;
        public void UpdateNpcAnimation(CallReducerFlags flags) => UpdateNpcAnimationFlags = flags;
    }
}
