// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActiveTradeComponent
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "trade_session_entity_id")]
        public ulong TradeSessionEntityId;

        public ActiveTradeComponent(
            ulong EntityId,
            ulong TradeSessionEntityId
        )
        {
            this.EntityId = EntityId;
            this.TradeSessionEntityId = TradeSessionEntityId;
        }

        public ActiveTradeComponent()
        {
        }
    }
}
