// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Chunk
    {
        [DataMember(Name = "chunk_id")]
        public ulong ChunkId;
        [DataMember(Name = "position")]
        public ChunkPosition Position;

        public Chunk(
            ulong ChunkId,
            ChunkPosition Position
        )
        {
            this.ChunkId = ChunkId;
            this.Position = Position;
        }

        public Chunk()
        {
            this.Position = new();
        }
    }
}
