// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Config
    {
        [DataMember(Name = "version")]
        public uint Version;
        [DataMember(Name = "max_player_inventory_slots")]
        public uint MaxPlayerInventorySlots;
        [DataMember(Name = "trading_slots")]
        public uint TradingSlots;
        [DataMember(Name = "chunk_terrain_resolution")]
        public uint ChunkTerrainResolution;
        [DataMember(Name = "chunk_splat_resolution")]
        public uint ChunkSplatResolution;
        [DataMember(Name = "chunk_size")]
        public double ChunkSize;
        [DataMember(Name = "terrain_seed")]
        public uint TerrainSeed;
        [DataMember(Name = "entity_density")]
        public uint EntityDensity;
        [DataMember(Name = "min_spawn_range")]
        public float MinSpawnRange;
        [DataMember(Name = "max_spawn_range")]
        public float MaxSpawnRange;
        [DataMember(Name = "npc_detection_range")]
        public float NpcDetectionRange;

        public Config(
            uint Version,
            uint MaxPlayerInventorySlots,
            uint TradingSlots,
            uint ChunkTerrainResolution,
            uint ChunkSplatResolution,
            double ChunkSize,
            uint TerrainSeed,
            uint EntityDensity,
            float MinSpawnRange,
            float MaxSpawnRange,
            float NpcDetectionRange
        )
        {
            this.Version = Version;
            this.MaxPlayerInventorySlots = MaxPlayerInventorySlots;
            this.TradingSlots = TradingSlots;
            this.ChunkTerrainResolution = ChunkTerrainResolution;
            this.ChunkSplatResolution = ChunkSplatResolution;
            this.ChunkSize = ChunkSize;
            this.TerrainSeed = TerrainSeed;
            this.EntityDensity = EntityDensity;
            this.MinSpawnRange = MinSpawnRange;
            this.MaxSpawnRange = MaxSpawnRange;
            this.NpcDetectionRange = NpcDetectionRange;
        }

        public Config()
        {
        }
    }
}
