// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InventoryComponent
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "pockets")]
        public System.Collections.Generic.List<Pocket> Pockets;

        public InventoryComponent(
            ulong EntityId,
            System.Collections.Generic.List<Pocket> Pockets
        )
        {
            this.EntityId = EntityId;
            this.Pockets = Pockets;
        }

        public InventoryComponent()
        {
            this.Pockets = new();
        }
    }
}
