// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NpcComponent
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "model")]
        public string Model;
        [DataMember(Name = "next_action")]
        public ulong NextAction;

        public NpcComponent(
            ulong EntityId,
            string Model,
            ulong NextAction
        )
        {
            this.EntityId = EntityId;
            this.Model = Model;
            this.NextAction = NextAction;
        }

        public NpcComponent()
        {
            this.Model = "";
        }
    }
}
