// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Pocket
    {
        [DataMember(Name = "item_id")]
        public uint ItemId;
        [DataMember(Name = "pocket_idx")]
        public uint PocketIdx;
        [DataMember(Name = "item_count")]
        public int ItemCount;

        public Pocket(
            uint ItemId,
            uint PocketIdx,
            int ItemCount
        )
        {
            this.ItemId = ItemId;
            this.PocketIdx = PocketIdx;
            this.ItemCount = ItemCount;
        }

        public Pocket()
        {
        }
    }
}
