// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ResourceComponent
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "health")]
        public byte Health;
        [DataMember(Name = "resource_id")]
        public byte ResourceId;
        [DataMember(Name = "max_health")]
        public byte MaxHealth;
        [DataMember(Name = "item_yield_id")]
        public byte ItemYieldId;
        [DataMember(Name = "item_yield_quantity")]
        public byte ItemYieldQuantity;

        public ResourceComponent(
            ulong EntityId,
            byte Health,
            byte ResourceId,
            byte MaxHealth,
            byte ItemYieldId,
            byte ItemYieldQuantity
        )
        {
            this.EntityId = EntityId;
            this.Health = Health;
            this.ResourceId = ResourceId;
            this.MaxHealth = MaxHealth;
            this.ItemYieldId = ItemYieldId;
            this.ItemYieldQuantity = ItemYieldQuantity;
        }

        public ResourceComponent()
        {
        }
    }
}
