// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TradeSessionComponent
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "initiator_entity_id")]
        public ulong InitiatorEntityId;
        [DataMember(Name = "acceptor_entity_id")]
        public ulong AcceptorEntityId;
        [DataMember(Name = "acceptor_offer_inventory_entity_id")]
        public ulong AcceptorOfferInventoryEntityId;
        [DataMember(Name = "initiator_offer_inventory_entity_id")]
        public ulong InitiatorOfferInventoryEntityId;
        [DataMember(Name = "approved_by_initiator")]
        public bool ApprovedByInitiator;
        [DataMember(Name = "approved_by_acceptor")]
        public bool ApprovedByAcceptor;

        public TradeSessionComponent(
            ulong EntityId,
            ulong InitiatorEntityId,
            ulong AcceptorEntityId,
            ulong AcceptorOfferInventoryEntityId,
            ulong InitiatorOfferInventoryEntityId,
            bool ApprovedByInitiator,
            bool ApprovedByAcceptor
        )
        {
            this.EntityId = EntityId;
            this.InitiatorEntityId = InitiatorEntityId;
            this.AcceptorEntityId = AcceptorEntityId;
            this.AcceptorOfferInventoryEntityId = AcceptorOfferInventoryEntityId;
            this.InitiatorOfferInventoryEntityId = InitiatorOfferInventoryEntityId;
            this.ApprovedByInitiator = ApprovedByInitiator;
            this.ApprovedByAcceptor = ApprovedByAcceptor;
        }

        public TradeSessionComponent()
        {
        }
    }
}
