// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TransformComponent
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "pos")]
        public StdbVector3 Pos;
        [DataMember(Name = "rot")]
        public StdbQuaternion Rot;

        public TransformComponent(
            ulong EntityId,
            StdbVector3 Pos,
            StdbQuaternion Rot
        )
        {
            this.EntityId = EntityId;
            this.Pos = Pos;
            this.Rot = Rot;
        }

        public TransformComponent()
        {
            this.Pos = new();
            this.Rot = new();
        }
    }
}
