// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Tree
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "chunk")]
        public ChunkPosition Chunk;
        [DataMember(Name = "tree_idx")]
        public ushort TreeIdx;
        [DataMember(Name = "x")]
        public float X;
        [DataMember(Name = "y")]
        public float Y;
        [DataMember(Name = "scale")]
        public float Scale;

        public Tree(
            ulong EntityId,
            ChunkPosition Chunk,
            ushort TreeIdx,
            float X,
            float Y,
            float Scale
        )
        {
            this.EntityId = EntityId;
            this.Chunk = Chunk;
            this.TreeIdx = TreeIdx;
            this.X = X;
            this.Y = Y;
            this.Scale = Scale;
        }

        public Tree()
        {
            this.Chunk = new();
        }
    }
}
